README.md

The correct API is not fs.writeFileSink, its fs.writeFileSync

Fix typo in example's function

---

src/bn128.js
src/verifier_original.js

Some forgotten commas prevent Angular from building the app, when snarkjs is used in the frontend.

Removed useless commas

---

templates/verifier_groth.sol
templates/verifier_kimleeoh.sol
templates/verifier_original.sol

The issue was first seen here: https://github.com/kobigurk/semaphore/issues/16
Based on the fix here: https://github.com/HarryR/ethsnarks/pull/141/files#diff-16b9d31d5ce4453863d191dd65657417R85

Ensures public inputs are less than the scalar field size

---

templates/verifier_groth.sol
templates/verifier_kimleeoh.sol
templates/verifier_original.sol

This PR adds revert reason strings to the check which ensures that each public input is less than the scalar field size. This will make contract debugging easier.

Added revert reasons to the snark_scalar_field checks in verifier.sol templates

---

src/stringifybigint.js

This PR is a quick fix of `stringifyBigInts` function. 
In case a browser does not support BigInt natively, previous check `(o instanceof bigInt)` does not work cause [bigint.js](https://github.com/iden3/snarkjs/blob/master/src/bigint.js#L224) exports a `function` (not a `Class`) of `bigInt` then. So the `instanceof` will never return `true`.  
Anyway, `o` has some defined bigInt methods (such as `isZero`)
But I think it would be better to define `wBigInt` as a Class.
The issue related to [websnark](https://github.com/iden3/websnark/blob/a0680804a5a3ab1ec397566453da275a9e2db6ca/tools/stringifybigint.js#L26) too.

instanceof bigInt [ bug fix ]

---

src/binfileutils.js
src/powersoftau_utils.js

These simple commands failed on my MacOS
```
snarkjs powersoftau new bn128 12 pot12_0000.ptau -v
snarkjs powersoftau contribute pot12_0000.ptau pot12_0001.ptau --name="First contribution" -v
[ERROR] snarkJS: Error: pot12_0000.ptau: File has no  contributions
at readContributions (/Users/zhangzhuo/repos/zk/newzkmm/node_modules/snarkjs/build/cli.cjs:1912:30)
at contribute (/Users/zhangzhuo/repos/zk/newzkmm/node_modules/snarkjs/build/cli.cjs:3284:33)
```
I checked why this error happened. Then I find the output file pot12_0000.ptau is wrong in fact. 
```
$ xxd pot12_0000.ptau|head
00000000: 7074 6175 0100 0000 0700 0000 0100 0000  ptau............
00000010: 2c00 0000 0000 0000 2000 0000 47fd 7cd8  ,....... ...G.|.
00000020: 168c 203c 8dca 7168 916a 8197 5d58 8181  .. <..qh.j..]X..
00000030: …
```

Fix the bug of corrupt binfile due to missing await

---

cli.js

The index of the verification key filepath parameter should be 1, not 2.

Fixes the zkey export verificationkey command to allow the user to specify the output path of the verification key

---

config/rollup.cjs.config.js
config/rollup.cli.config.js
config/rollup.iife.config.js
config/rollup.iife_min.config.js
package-lock.json
package.json

I updated the rollup configurations to use the latest official plugins and swapped out the `ignore` plugin for the official `virtual` plugin.
I didn't regenerate the bundles because the diffs are really weird. It seems that there are a bunch of dependencies that are duped in the tree and cause things like `big-integer` and `wasmcurves` to be in the bundles more than once. I pinged in the telegram group about this.
I have some additional work that I want to submit, but it should probably come after those are cleaned up.

chore: convert rollup plugins to latest official

---

src/wtns_calculate.js
src/wtns_debug.js

Once https://github.com/iden3/circom_runtime/pull/8 is merged and released, these imports need to be updated.

fix: new import style from circom_runtime

---

config/rollup.iife.config.js
config/rollup.iife_min.config.js

Once https://github.com/iden3/ffjavascript/pull/11 is merged and released, these changes will ensure the `browser` field is correctly used by Rollup for the browser bundles.

fix: ensure browser field in package.json are used by rollup

---

README.md

Just two instances of `s/contraints/constraints`.

Update README.md to fix typos.

---

config/rollup.cjs.config.js
config/rollup.cli.config.js
config/rollup.iife.config.js
config/rollup.iife_min.config.js

Relies on https://github.com/iden3/ffjavascript/pull/12 and https://github.com/iden3/ffjavascript/pull/13
This pulls in some new rollup patterns applied to the other repositories. For the commonjs builds, it ensures that no node_module is bundled into the output, even when dependencies are added to the package.json
For the browser, it sets up some additional config that is used for the `web-worker` abstraction in the ffjavascript project.
Additionally, I made the minified build just depend on the iife config, so they don't need to be updated separately.

chore: update rollup patterns

---

config/rollup.iife.config.js
package.json

This fixes the iife builds by injecting a empty object as the "global" reference so the underlying modules don't error when trying to access.
It seems like this problem was introduced when all the underlying modules were converted to ESM because the iife build was relying on rollup's `commonjs` plugin to replace the `global` reference with an empty object. Now that the plugin doesn't run for those modules, it isn't replaced.
Fixes #77

fix: inject global object into browser build (fixes #77)

---

package.json

I was able to get the required APIs added into blake2b-wasm so SnarkJS can switch back to the upstream library. See https://github.com/mafintosh/blake2b-wasm/pull/16
Closes #96
Closes #61

Switch to upstream blake2b-wasm

---

templates/verifier_plonk.sol.ejs

The `sol` file generated using `solidityverifier` uses datatype `uint16` for variable `n`. This does not work for large number of maxConstraints, specifically when `power > 16`. The PR aims at adjusting the `uint` size based on `power`. 
A similar PR is is present at [https://github.com/iden3/snarkjs/pull/101](https://github.com/iden3/snarkjs/pull/101). However, it uses `uint32` even if the number of constraints is low enough.

fix: uint size for higher powers in PLONK verifier sol

---

config/rollup.iife.config.js
package.json

Once #118 is completed, we should be able to remove the global shim in the browser build because ffjavascript will be using `globalThis` instead of `global`.

fix: Remove global shim from browser build

---

src/clprocessor.js

the code returned by the functions was not transferred to the program's exit code.

fix bug on exit code

---

src/wtns_debug.js

This splits the `<--` and `-->` arrows into 2 separate strings to avoid a false-positive rejection from Secure ECMAScript.

fix: Add workaround for SES that reject arrow strings

---

src/plonk_setup.js

Commit https://github.com/iden3/snarkjs/commit/f5ebdc1d08fc569f2f7310e093dfae108b312817 added `global.gc` calls for the `plonk_setup`. However, the `global` variable is not available in the browser. Converting this to `globalThis` will ensure this works in nodejs and the browser.

fix: Update plonk GC call to use globalThis

---

build/cli.cjs
cli.js

I debugged the failures in the "test tutorial" CI and found that the `zkey.importBellman` function returns true if the import was successful. Returning `true` is the same as returning `1` to the CLI tool, which causes an incorrect exit. We need to check that the `isValid` return is true and then return a `0` exit code, like other functions.

fix: Ensure zkey import bellman command exits with correct code

---

src/groth16_prove.js
src/plonk_prove.js
src/zkey_utils.js

Speeds up proving by caching zkey getCurve call when reading headers and avoiding double calls in grothProve. On a smallish circuit (https://github.com/nalinbhardwaj/snarky-sudoku) this amounts to a ~30% reduction, which is pretty significant IMO:
**Before:**
*~4 seconds runtime*
**After:**
*~3 seconds runtime*
Branched on #121

feat: Improve proving speed by caching zkey curve

---

build/cli.cjs
cli.js
package-lock.json
package.json

Fixes #193 (and a whole set of related issues when trying to serialize large data sets).
I think we probably should use `bfj` to read JSON too so these large files can be loaded again, but I need to work with someone to test that.

fix: Use bfj library to stringify JSON in CLI commands

---

cli.js

`power` argument is checked if it fits within the range while this check pass for `NaN`, which I suppose is not valid.
Also generated file contains `NaN` in the name.
Steps to reproduce:
`snarkjs powersoftau new bn128 new.ptau`
output:
`powersOfTauNaN_0000.ptau`
Generated file cannot be also exported to json:
```
snarkjs ptej powersOfTauNaN_0000.ptau powers.json
[ERROR] snarkJS: Error: Invalid section size reading
at Object.endReadSection (/Users/kziemianek/.nvm/versions/node/v18.8.0/lib/node_modules/snarkjs/node_modules/@iden3/binfileutils/build/main.cjs:107:74)
at exportSection (/Users/kziemianek/.nvm/versions/node/v18.8.0/lib/node_modules/snarkjs/build/cli.cjs:2950:39)
at async exportJson (/Users/kziemianek/.nvm/versions/node/v18.8.0/lib/node_modules/snarkjs/build/cli.cjs:2922:18)
at …
```

fix: check power is number

---

templates/verifier_fflonk.sol.ejs

- Update the calldata arrays to fixed arrays
- Fix one line identation
- Erase the mstore at the end of the execution that updates the "free memory pointer" since the following lines no more memory is allocated, ( basically only an mstore and return happen)

Small fixes

---

.github/workflows/tests.yml

Due to https://github.com/NomicFoundation/hardhat/issues/3877, we're disabling the node 20 tests and pinning node 18 to 18.15.0 for the solidity tests.

chore(ci): Workaround hardhat + node bug

---

build/cli.cjs
cli.js

Fixes #366
This fixes usage of various commands in the CLI. Generally, we want to avoid returning function calls because they return values that might be used in application code; however the CLI expect integers to be returned so it can call `process.exit(code)`.
@chentihe please try this code and see if it works.

fix(cli): Correctly return status codes instead of values

---

templates/verifier_groth16.sol.ejs

The Groth16Verifier contract is not correctly generating codes to checking that public signals are within the scalar field's range. Signals should be less than `r` instead of `q` in the contract's context.
See https://github.com/iden3/snarkjs/issues/479
EDIT:
This may actually be a security vulnerability for small public signals that is less than `q - r`. And because `q-r = 147946756881789318990833708069417712966` is not that small, many use cases may fall into this range.
Exploit:
A simple circom circuit accepting a value less than 100.
```
pragma circom 2.1.5;
include "circomlib/circuits/comparators.circom";
template Main() {
signal input v;
signal output tinyVal;
tinyVal <== v;
component lte = LessEqThan(252);
lte.in[0] <== v;
lte.in[1] <== 100;
lte.out === 1;
}
component main = …
```

fix: Groth16Verifier solidity scalar size check. (security vulnerability)

---

.github/workflows/tests.yml
.github/workflows/tutorial.yml
README.md
smart_contract_tests/package-lock.json
smart_contract_tests/package.json

* Do not run tests twice for each pull request update (was `on: [push, pull_request]`)
* Update node versions in ci tests.
* Remove tests specific for node v12.
* Update hardhat in smart_contract_tests to remove previous node version restrictions because of (now fixed) hardhat bug

Fix CI tests

---

browser_tests/package-lock.json
browser_tests/package.json
package-lock.json
package.json

Fixes #476, #97
Following dependencies were updated:
* https://github.com/iden3/ffjavascript/releases/tag/v0.3.0
* https://github.com/iden3/circom_runtime/releases/tag/v0.1.25
* https://github.com/iden3/binfileutils/releases/tag/v0.0.12
* https://github.com/iden3/r1csfile/releases/tag/v0.0.48
Changes in packages can be seen on respective package release pages (and all changes at once can be viewed with Full Changelog link at the bottom of the description).

Bump dependency version

---

main.js

Export curves to allow terminating wasm threads (curve.terminate) from outside code.
Fixes #494 with the following changes in the[ bug reproduction code](https://github.com/dovgopoly/snarkjs-issue/blob/master/main.js):
```js
async function main() {
const r1cs = "rsc/Multiplier.r1cs";
const ptau = "rsc/powersOfTau28_hez_final_08.ptau";
const zkey = "rsc/Multiplier.zkey"
// initializes the curve object controlling wasm threads
let curve = await snarkjs.curves.getCurveFromName("bn128");
await snarkjs.r1cs.info(r1cs, console);
await snarkjs.zKey.newZKey(r1cs, ptau, zkey, console);
// terminates threads
curve.terminate();
}
```

Export curves

---

src/wtns_calculate.js

The `WitnessCalculatorBuilder` constructor allows for an `options` object which is not being passed through even though it is in scope. This PR fixes this problem
See [this PR](https://github.com/iden3/circom_runtime/pull/107) in circom_runtime

Pass options object to WitnessCalculatorBuilder

---

.github/workflows/tests.yml
.github/workflows/tutorial.yml
README.md

Update GHA nodejs versions and switch to latest circom v2 for tutorial tests

Update GHA nodejs versions and use circom v2 for tests
